### ISSUE TITLE
add test metadata bundle for GDC testing

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-global-services-testing#15]
Create a zipfile of test metadata records that can be used for GDC testing, including at least 2-3 examples of each of the following:

- valid WCMP2
- invalid WCMP2
  - missing required fields
  - invalid `properties.wmo:dataPolicy`
  - bad `geometry`
  - bad `id` format
- malformed JSON

**Comment by shirley-xuelei** [comment]
@tomkralidis please find the attached test metadata records.
[Test metadata records (GDC CMA).zip](https://github.com/user-attachments/files/15756579/Test.metadata.records.GDC.CMA.zip)

**Comment by tomkralidis** [comment]
Thank you @shirley-xuelei.  PR now in #18 to add to repo.
