### ISSUE TITLE
determine performance benchmark test tool

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-global-services-testing#32]
Agree on tooling to execute performance tests with parametertization (number of requests/connections, users/concurrency):

- MQTT: mqttx, which has a `bench` subcommand to help measure performance
- HTTP:
  - [Apache bench](https://httpd.apache.org/docs/2.4/programs/ab.html)
  - [JMeter](https://jmeter.apache.org)
  - [Siege](https://github.com/JoeDog/siege)
  - other options?

**Comment by golfvert** [comment]
I have used (a bit) jmeter a long time ago. I found it rather hard to use and not very convenient. Having looked at the manual of Apache Bench it seems fine.
This is just gut feeling, though. No real experience...

**Comment by antje-s** [comment]
I have now done my own first tests with ab (Apache bench) and find the tool easy to use - it was a good idea to change over

**Comment by tomkralidis** [comment]
Thanks for the feedback.  At this point we have concluded that `mqttx-cli` and `ab` are the tooling we use/build against as part of performance testing.
