### ISSUE TITLE
deploy prometheus in dev/test space for tests

### ISSUE THREAD

**Issue by jmaxmarno** [wmo-im/wis2-global-services-testing#34]
This is needed to aggregate metrics from all global services being tested to standardize the metrics ingestion, and provide api functionality for tests relying on metrics comparison for validation.
need to find a place to put this, new instance?
example:

https://github.com/wmo-im/wis2-gdc/blob/main/docker-compose.yml#L63-L70

**Comment by jmaxmarno** [comment]
@antje-s

**Comment by golfvert** [comment]
gm.wis2dev.io exists and is already fetching all metrics from Global Services.
